# Generated by Django 4.2.5 on 2023-09-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='status_tag',
            field=models.CharField(default='active', max_length=255),
        ),
    ]
