# Generated by Django 4.2.5 on 2023-09-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_campaign', '0002_subscriber_status_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='status_tag',
            field=models.CharField(default='', max_length=255),
        ),
    ]
